name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install pipenv
      run: |
          python -m pip install --no-cache-dir --upgrade pipenv
          
    - name: Install dependencies
      run: |
        pipenv --python 3.11
        pipenv install --dev --deploy

    - name: Run tests with coverage
      run: pipenv run coverage run -m pytest

    - name: Generate coverage report
      run: pipenv run coverage report -m

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Only required for private repos
        files: ./coverage.xml
        fail_ci_if_error: false
