name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv
      run: |
          python -m pip install --no-cache-dir --upgrade pipenv
          
    - name: Install dependencies
      run: |
        pipenv --python 3.8
        pipenv install --dev --deploy

    - name: Run tests with coverage
      run: |
        pipenv run coverage run -m pytest/unit
        pipenv run coverage run -m pytest/e2e

    - name: Generate coverage report
      run: pipenv run coverage report -m

    - name: Save coverage report xml
      run : |
        pipenv run coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml