name: Publish a Python distribution to PyPI

permissions: write-all

on:
  push:
    branches:
      - main  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install dependencies
        run: |
          pipenv --python 3.8
          pipenv install
      - name: bump version
        run: |
          version=$(grep -oP 'version\s*=\s*"\K[^"]+' omnibridge/version.py)
          IFS="." read -ra version_parts <<< "$version"
          patch=$(( ${version_parts[2]} + 1 ))
          new_version="${version_parts[0]}.${version_parts[1]}.$patch"
          sed -i "s/version = \"${version}\"/version = \"${new_version}\"/" omnibridge/version.py
      - name: Commit and push changes
        run: |
          git config user.name "pypi publish workflow"
          git config user.email "your.email@example.com"
          git add omnibridge/version.py
          git commit --reuse-message="HEAD@{0}"
          git push origin
      - name: Create source distribution
        run: |
          python setup.py sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
