name: Test

on: [ push, pull_request ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install dependencies
        run: |
          pipenv --python 3.11
          pipenv install
          
      - name: Run tests
        run: |
          pipenv run python -m pytest tests
