name: Update Version
permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  increment_version:
    if: "!contains(fromJson(steps.check_latest_pr.outputs.pr_labels), 'version-update')"
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Check latest PR labels
      id: check_latest_pr
      run: |
        pr_labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls?state=closed | jq -r '[.[] | select(.merged_at != null) | .labels[].name] | join(",")')
        echo "::set-output name=pr_labels::${pr_labels}"

    - name: Increment version
      run: |
        version=$(grep -oP 'version\s*=\s*"\K[^"]+' omnibridge/version.py)
        IFS="." read -ra version_parts <<< "$version"
        patch=$(( ${version_parts[2]} + 1 ))
        new_version="${version_parts[0]}.${version_parts[1]}.$patch"
        sed -i "s/version = \"${version}\"/version = \"${new_version}\"/" omnibridge/version.py

    - name: generate branch name
      run: |
        branch_name="update-version-$(date +'%Y%m%d%H%M%S')"
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Increment version"
        body: "This PR increments the version in `version.py`."
        branch: ${{ env.BRANCH_NAME }}
        labels: "version-update"
